name: hornblasters
description: HornBlasters makes and sells the worlds loudest horns for your ride! Founded in 2002, we created the market and stand behind everything we sell. Whether its a train horn for your truck or an air horn for your golf cart, you name the vehicle, we have a loud horn for it! Quality products. Quality support.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.4
  firebase_core:
  cloud_firestore:
  video_player: ^2.4.4
  web_scraper: ^0.1.4
  audioplayers: ^0.20.1
  onesignal_flutter: ^3.3.2
  flutter_launcher_icons: ^0.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon1.png"
  adaptive_icon_background: "#077CFB"
  adaptive_icon_foreground: "assets/images/icon1.png"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: AlternateGot
      fonts:
        - asset: assets/fonts/AlternateGotNo3D.ttf
    - family: GaleanaCondensed
      fonts:
        - asset: assets/fonts/GaleanaCondensed-HeavyIt.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

